// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PublicResolver$Type } from "./PublicResolver.js";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PublicResolver"]: PublicResolver$Type;
    ["contracts/resolvers/PublicResolver.sol:PublicResolver"]: PublicResolver$Type;
  }

  interface ContractTypesMap {
    ["PublicResolver"]: GetContractReturnType<PublicResolver$Type["abi"]>;
    ["contracts/resolvers/PublicResolver.sol:PublicResolver"]: GetContractReturnType<PublicResolver$Type["abi"]>;
  }
}
