// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { UniversalResolver$Type } from "./UniversalResolver.js";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["UniversalResolver"]: UniversalResolver$Type;
    ["contracts/universalResolver/UniversalResolver.sol:UniversalResolver"]: UniversalResolver$Type;
  }

  interface ContractTypesMap {
    ["UniversalResolver"]: GetContractReturnType<UniversalResolver$Type["abi"]>;
    ["contracts/universalResolver/UniversalResolver.sol:UniversalResolver"]: GetContractReturnType<UniversalResolver$Type["abi"]>;
  }
}
