// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ENSRegistry$Type } from "./ENSRegistry.js";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ENSRegistry"]: ENSRegistry$Type;
    ["contracts/registry/ENSRegistry.sol:ENSRegistry"]: ENSRegistry$Type;
  }

  interface ContractTypesMap {
    ["ENSRegistry"]: GetContractReturnType<ENSRegistry$Type["abi"]>;
    ["contracts/registry/ENSRegistry.sol:ENSRegistry"]: GetContractReturnType<ENSRegistry$Type["abi"]>;
  }
}
