name: Formatting

on:
  push:
    branches: [main]
  pull_request:

jobs:
  formatting:
    name: Code formatting check
    runs-on: ubuntu-latest
    steps:
      - name: Cache git folder
        uses: actions/cache@v4
        with:
          path: .git
          key: git-folder

      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - run: bun install --frozen-lockfile

      - name: Run lint
        run: bun --filter contracts lint